import Providers from "@/app/ui/providers";

import { Overpass, Roboto } from "next/font/google";

import "@/app/ui/globals.css";

import type { Metadata } from "next";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const overpass = Overpass({
  variable: "--font-overpass",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${overpass.variable} pb-20 antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
